[dataset]
data_dir = "./data"
img_size = 32
batch_size = 512
num_workers = 4
use_cache = true

[augmentation]
# 数据增强参数
h_flip_prob = 0.5      # 水平翻转概率
v_flip_prob = 0.0      # 垂直翻转概率
rotation_degrees = 15  # 旋转角度范围
brightness = 0.2       # 亮度变化范围
contrast = 0.2         # 对比度变化范围
saturation = 0.2       # 饱和度变化范围
hue = 0.0              # 色调变化范围
translate = 0.1        # 平移范围
scale = 0.1            # 缩放范围
random_crop = false    # 随机裁剪
crop_scale_min = 0.8   # 随机裁剪时的最小比例
blur_prob = 0.0        # 高斯模糊概率
blur_kernel_size = 3   # 高斯模糊核大小
grayscale_prob = 0.0   # 随机灰度转换概率
use_random_erase = false # 随机擦除
erase_prob = 0.1       # 随机擦除概率

[model]
model_name = "alexnet"
drop_out = 0.5         # 修改参数名称为drop_out
use_layer_norm = false # 是否启用层归一化
pretrained = ""        # 预训练模型路径，为空则不使用预训练

[training]
epochs = 150
lr = 1.0e-3
min_lr = 1.0e-6
weight_decay = 5.0e-4
seed = 42
save_freq = 20
use_amp = true         # 是否使用混合精度训练

[hardware]
gpus = [1]             # 指定要使用的GPU ID列表
