[dataset]
data_dir = "./data/elbow"
img_size = 320
batch_size = 128
num_workers = 8

[model]
model_name = "inception_v3"  # 或 "swin_transformer"
drop_rate = 0.0
drop_path_rate = 0.1
pretrained = ""  # 预训练模型路径，为空则不使用预训练

[training]
epochs = 100
lr = 1.0e-4
min_lr = 1.0e-6
weight_decay = 0.05
seed = 42
save_freq = 10
use_amp=true  # 是否使用混合精度训练